export { default as Home } from './Home'
export { default as About } from './About'
export { default as Work } from './Work'
export { default as Gear } from './Gear'
export { default as Gallery } from './Gallery'
export { default as Contact } from './Contact'
